### ISSUE TITLE
env.emit not a function in Sassdoc build

### ISSUE THREAD

**Issue by davidknezic** [axa-group/web-toolkit#10]
Any clue @elessar-ch?

```
[docs:build] 11:51:35 AM Start metalsmith build!
[docs:build] 11:51:35 AM Started watch
[docs:build] 11:51:35 AM Excluded draft pages
[docs:build] /Users/davidknezic/Repositories/web-toolkit/node_modules/sassdoc/dist/parser.js:52
[docs:build]       env.emit('warning', new errors.Warning(warning.message));
[docs:build]           ^
[docs:build]
[docs:build] TypeError: env.emit is not a function
[docs:build]     at CommentParser.<anonymous> (/Users/davidknezic/Repositories/web-toolkit/node_modules/sassdoc/dist/parser.js:52:11)
[docs:build]     at emitOne (events.js:90:13)
[docs:build]     at CommentParser.emit (events.js:182:7)
[docs:build]     at CommentParser.<anonymous> (/Users/davidknezic/Repositories/web-toolkit/node_modules/cdocparser/index.js:335:16)
[docs:build]     at Array.forEach (native)
[docs:build]     at CommentParser.parseComment (/Users/davidknezic/Repositories/web-toolkit/node_modules/cdocparser/index.js:284:19)
[docs:build]     at CommentParser.<anonymous> (/Users/davidknezic/Repositories/web-toolkit/node_modules/cdocparser/index.js:414:27)
[docs:build]     at Array.forEach (native)
[docs:build]     at CommentParser.parse (/Users/davidknezic/Repositories/web-toolkit/node_modules/cdocparser/index.js:413:14)
[docs:build]     at [object Object].Parser.parse (/Users/davidknezic/Repositories/web-toolkit/node_modules/scss-comment-parser/index.js:202:29)
[docs:build]     at Parser.parse (/Users/davidknezic/Repositories/web-toolkit/node_modules/sassdoc/dist/parser.js:57:28)
[docs:build]     at /Users/davidknezic/Repositories/web-toolkit/lib/sassdoc-data.js:12:42
[docs:build]     at Timeout.next [as _onTimeout] (/Users/davidknezic/Repositories/web-toolkit/node_modules/metalsmith-branch/node_modules/ware/lib/index.js:68:8)
[docs:build]     at tryOnTimeout (timers.js:224:11)
[docs:build]     at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by davidknezic** [comment]
Fixed by #11
