### ISSUE TITLE
Metalsmith build crashes with max call stack size exceeded

### ISSUE THREAD

**Issue by davidknezic** [axa-group/web-toolkit#9]
This just happened out of the blue:

```
[docs:build] 11:18:02 AM Remove includes and layouts from metalsmith
[docs:build] /Users/davidknezic/Repositories/web-toolkit/node_modules/babel-polyfill/node_modules/core-js/modules/es6.symbol.js:224
[docs:build]     return _stringify.apply($JSON, args);
[docs:build]                       ^
[docs:build]
[docs:build] RangeError: Maximum call stack size exceeded
[docs:build]     at join (native)
[docs:build]     at Object.stringify (native)
[docs:build]     at Object.stringify (/Users/davidknezic/Repositories/web-toolkit/node_modules/babel-polyfill/node_modules/core-js/modules/es6.symbol.js:224:23)
[docs:build]     at addJSONtoMetalsmith (/Users/davidknezic/Repositories/web-toolkit/node_modules/metalsmith-lunr/lib/index.js:63:34)
[docs:build]     at /Users/davidknezic/Repositories/web-toolkit/node_modules/metalsmith-lunr/lib/index.js:10:5
[docs:build]     at next (/Users/davidknezic/Repositories/web-toolkit/node_modules/metalsmith-branch/node_modules/ware/lib/index.js:68:8)
[docs:build]     at /Users/davidknezic/Repositories/web-toolkit/lib/metalsmith-navigation.js:35:12
[docs:build]     at next (/Users/davidknezic/Repositories/web-toolkit/node_modules/metalsmith-branch/node_modules/ware/lib/index.js:68:8)
[docs:build]     at /Users/davidknezic/Repositories/web-toolkit/lib/metalsmith-relate.js:18:12
[docs:build]     at next (/Users/davidknezic/Repositories/web-toolkit/node_modules/metalsmith-branch/node_modules/ware/lib/index.js:68:8)
[docs:build]     at /Users/davidknezic/Repositories/web-toolkit/node_modules/metalsmith-filepath/lib/index.js:16:3
[docs:build]     at Timeout.next [as _onTimeout] (/Users/davidknezic/Repositories/web-toolkit/node_modules/metalsmith-branch/node_modules/ware/lib/index.js:68:8)
[docs:build]     at tryOnTimeout (timers.js:224:11)
[docs:build]     at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by davidknezic** [comment]
It happens when I add an inlined base64 image to the `page.hbs` layout.

```
[docs:build]     at addJSONtoMetalsmith (/Users/davidknezic/Repositories/web-toolkit/node_modules/metalsmith-lunr/lib/index.js:63:34)
```

Disabling lunr lets me continue working for now.
